In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import preprocessing
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix, recall_score, precision_score

In [ ]:
data = pd.read_csv("play_tennis.csv")
data = data.drop(["day"],axis = 1)
data.head()

outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

In [ ]:
X = data.iloc[:,:4]
y = data.iloc[:,-1]
print("independant variables: \n", X)
print("Dependant var: \n", y)

independant variables: 
      outlook  temp humidity    wind
0      Sunny   Hot     High    Weak
1      Sunny   Hot     High  Strong
2   Overcast   Hot     High    Weak
3       Rain  Mild     High    Weak
4       Rain  Cool   Normal    Weak
5       Rain  Cool   Normal  Strong
6   Overcast  Cool   Normal  Strong
7      Sunny  Mild     High    Weak
8      Sunny  Cool   Normal    Weak
9       Rain  Mild   Normal    Weak
10     Sunny  Mild   Normal  Strong
11  Overcast  Mild     High  Strong
12  Overcast   Hot   Normal    Weak
13      Rain  Mild     High  Strong
Dependant var: 
 0      No
1      No
2     Yes
3     Yes
4     Yes
5      No
6     Yes
7      No
8     Yes
9     Yes
10    Yes
11    Yes
12    Yes
13     No
Name: play, dtype: object


In [ ]:
lab_enc = preprocessing.LabelEncoder()
for i in range(4):
  X.iloc[:,i] = lab_enc.fit_transform(X.iloc[:,i])
y = lab_enc.fit_transform(y)

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:1951: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[selected_item_labels] = value


In [ ]:
xtrain, xtest, ytrain, ytest = train_test_split(X, y, test_size=0.5, random_state=0)
print("Traindata: \n", xtrain, "\n", ytrain)
print("Testdata: \n", xtest, "\n", ytrain)


Traindata: 
     outlook  temp  humidity  wind
1         2     1         0     0
7         2     2         0     1
10        2     2         1     0
3         1     2         0     1
0         2     1         0     1
5         1     0         1     0
12        0     1         1     1 
 [0 0 1 1 0 0 1]
Testdata: 
     outlook  temp  humidity  wind
8         2     0         1     1
6         0     0         1     0
4         1     0         1     1
11        0     2         0     0
2         0     1         0     1
13        1     2         0     0
9         1     2         1     1 
 [0 0 1 1 0 0 1]


In [ ]:
gaus = GaussianNB()
mod = gaus.fit(xtrain,ytrain)
ypred = mod.predict(xtest)
print(ypred)
print(ytest)
print("MSE: ", mean_squared_error(ypred,ytest))

con_mat = confusion_matrix(ytest,ypred)
print("Confusion matrix: \n", con_mat)

[0 1 0 1 1 1 1]
[1 1 1 1 1 0 1]
MSE:  0.42857142857142855
Confusion matrix: 
 [[0 1]
 [2 4]]


In [ ]:
print(mod.score(xtest,ytest))
print(recall_score(ytest,ypred))
print(precision_score(ytest,ypred))

0.5714285714285714
0.6666666666666666
0.8


In [ ]:
#specificity
spec = con_mat[0,0]/con_mat[0,0]+con_mat[1,1]
#sensitivity
sens = con_mat[0,1]/con_mat[1,0]+con_mat[0,1]
print(spec)
print(sens)

nan
1.5


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in long_scalars
  
